name: ai_drafting_agent
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adwaita-icon-theme=49.0=unix_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311h0281608_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.1=hb03c661_0
  - aom=3.9.1=hac33072_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - blosc=1.21.6=hef167b5_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - coin3d=4.0.3=hd74d64a_2
  - contourpy=1.3.3=py311hdf67eae_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h5bd4931_0
  - double-conversion=3.3.1=h5888daf_0
  - epoxy=1.5.10=hb03c661_2
  - expat=2.7.3=hecca717_0
  - ffmpeg=7.1.1=gpl_h427a037_504
  - flann=1.9.2=h3ef53d8_3
  - fltk=1.3.10=hff38c0f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3778330_0
  - freecad=1.0.0=py311h088cda4_4
  - freeglut=3.2.2=ha6d2627_3
  - freeimage=3.18.0=h49ef1fa_24
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py311h52bc045_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.84.0=h07242d1_0
  - glib-tools=2.84.0=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - gmsh=4.15.0=h3eaee40_1
  - graphite2=1.3.14=hecca717_2
  - graphviz=12.2.1=h5ae0cbf_1
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - gtk3=3.24.43=h0c6a113_5
  - gts=0.7.6=h977cf35_4
  - harfbuzz=11.0.0=h76408a6_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.4=nompi_h2d575fe_105
  - hicolor-icon-theme=0.17=ha770c72_2
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=hde8ca8f_0
  - jasper=4.2.8=he3c4edf_0
  - jsoncpp=1.9.6=hf42df4d_1
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.3=hb700be7_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.4=h3f801dc_0
  - libass=0.17.3=h52826cd_2
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libboost=1.86.0=hed09d94_4
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_5
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_1
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.2=nompi_h5ddbaa4_116
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2025.0.0=hac27bb2_0
  - libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_0
  - libopenvino-auto-plugin=2025.0.0=h4d9b6c2_0
  - libopenvino-hetero-plugin=2025.0.0=h3f63f65_0
  - libopenvino-intel-cpu-plugin=2025.0.0=hac27bb2_0
  - libopenvino-intel-gpu-plugin=2025.0.0=hac27bb2_0
  - libopenvino-intel-npu-plugin=2025.0.0=hac27bb2_0
  - libopenvino-ir-frontend=2025.0.0=h3f63f65_0
  - libopenvino-onnx-frontend=2025.0.0=h6363af5_0
  - libopenvino-paddle-frontend=2025.0.0=h6363af5_0
  - libopenvino-pytorch-frontend=2025.0.0=h5888daf_0
  - libopenvino-tensorflow-frontend=2025.0.0=h630ec5c_0
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_0
  - libopus=1.6=h0fd0de7_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libpq=17.7=h5c52fec_1
  - libprotobuf=5.28.3=h6128344_1
  - libraw=0.21.4=h9969a89_0
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc7d488a_2
  - libspnav=1.1=h4ab18f5_2
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.3=h6569c3e_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.3=h5347b49_0
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h04c0eec_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib=3.10.8=py311h38be061_0
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.2=py311hdf67eae_1
  - multidict=6.7.0=py311h3778330_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h54a6638_1
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numpy=2.4.0=py311h2e04523_0
  - occt=7.8.1=all_h4c4714a_203
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openexr=3.4.4=h40f6f1d_1
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.26.0=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.3=h9ac818e_1
  - pcl=1.14.1=h679aaff_7
  - pcre2=10.44=hc749103_2
  - pillow=12.0.0=py311hf88fc01_2
  - pip=25.3=pyh8b19718_0
  - pivy=0.6.10=py311qt5h81a8827_0
  - pixman=0.46.4=h54a6638_1
  - ply=3.11=pyhd8ed1ab_3
  - proj=9.5.1=h0054346_0
  - propcache=0.3.1=py311h2dc5d0c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hac146a9_1
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.8.3=py311h9053184_0
  - python=3.11.14=hd63d673_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=py311h3778330_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.15=h993ce98_3
  - qt6-main=6.8.3=h6441bc3_1
  - rapidjson=1.1.0.post20240409=h3f2d84a_2
  - readline=8.3=h853b02a_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.24=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smesh=9.9.0.0=hb7ebc10_14
  - snappy=1.2.2=h03e3b7b_1
  - soqt=1.6.3=h21a1423_0
  - sqlite=3.51.1=hbc0de68_1
  - svt-av1=3.0.2=h5888daf_0
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.4=py311h41d9c34_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py311h49ec1c0_1
  - utfcpp=4.09=ha770c72_0
  - vtk=9.3.1=qt_py311h3d4e8c9_211
  - vtk-base=9.3.1=qt_py311h5011d52_211
  - vtk-io-ffmpeg=9.3.1=qt_py311h3d4e8c9_211
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wslink=2.5.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxmu=1.2.1=hb9d3cd8_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2025.1=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h3f2d84a_0
  - yarl=1.22.0=py311h3778330_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/shaf/anaconda3/envs/freecad_env
